config/routes.rb
The20times::Application.routes.draw do
  resources :authors

  resources :writers

  resources :articles

  get "static_pages/home"

  root 'static_pages#home'

  

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/author.rb
class Author < ActiveRecord::Base
    has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @authors = Author.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @articles = Article.all
    @authors = Author.all
  end

  # GET /articles/new
  def new
    @article = Article.new
    @authors = Author.all
  end

  # GET /articles/1/edit
  def edit
    @authors = Author.all
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @authors = Author.all

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :author_id, :topic, :content, :rank)
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @authors = Author.all
  end

  # GET /authors/new
  def new
    @authors = Author.all
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
    @authors = Author.all
  end

  # POST /authors
  # POST /authors.json
  def create
    @authors = Author.all
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render action: 'show', status: :created, location: @author }
      else
        format.html { render action: 'new' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    @authors = Author.all
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @authors = Author.all
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :summary)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @articles = Article.all
    @authors = Author.all
    @topics = [['politics', 'politics'],['coding', 'coding'],['science', 'science'],['stories', 'stories'],['music', 'music'],['books', 'books']]
  end
  def science
    @articles = Article.all
    @authors = Author.all
  end
  def art
    @articles = Article.all
    @authors = Author.all
  end
  def politics
    @articles = Article.all
    @authors = Author.all
  end
  def coding
    @articles = Article.all
    @authors = Author.all
  end
  def books
    @articles = Article.all
    @authors = Author.all
  end
  def stories
    @articles = Article.all
    @authors = Author.all
  end
  def music
    @articles = Article.all
    @authors = Author.all
  end
end

app/controllers/writers_controller.rb
class WritersController < ApplicationController
  before_action :set_writer, only: [:show, :edit, :update, :destroy]

  # GET /writers
  # GET /writers.json
  def index
    @writers = Writer.all
  end

  # GET /writers/1
  # GET /writers/1.json
  def show
  end

  # GET /writers/new
  def new
    @writer = Writer.new
  end

  # GET /writers/1/edit
  def edit
  end

  # POST /writers
  # POST /writers.json
  def create
    @writer = Writer.new(writer_params)

    respond_to do |format|
      if @writer.save
        format.html { redirect_to @writer, notice: 'Writer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @writer }
      else
        format.html { render action: 'new' }
        format.json { render json: @writer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /writers/1
  # PATCH/PUT /writers/1.json
  def update
    respond_to do |format|
      if @writer.update(writer_params)
        format.html { redirect_to @writer, notice: 'Writer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @writer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /writers/1
  # DELETE /writers/1.json
  def destroy
    @writer.destroy
    respond_to do |format|
      format.html { redirect_to writers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_writer
      @writer = Writer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def writer_params
      params.require(:writer).permit(:first_name, :last_name, :summary)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/writers_helper.rb
module WritersHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
    <%= render "shared/error_messages", :target => @article %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author_id %><%= mark_required(@article, :author_id) %><br>
    <%= f.collection_select(:author_id, Author.all, :id, :name, {include_blank: true})%>
  </div>
  <div class="field">
    <%= f.label :topic %><%= mark_required(@article, :topic) %><br>
    <%= f.select(:topic, [['politics', 'politics'],['coding', 'coding'],['science', 'science'],['stories', 'stories'],['music', 'music'],['books', 'books']])%>
  </div>
  <div class="field">
    <%= f.label :content %><%= mark_required(@article, :content) %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :rank %><%= mark_required(@article, :rank) %><br>
    <%= f.select(:rank, [['Major', 1],['Minor', 2]])%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class = 'article'>
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<div class = 'article'>
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Topic</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= Author.find(article.author_id).name %></td>
        <td><%= article.topic %></td>
        <td><%= article.content %></td>
        <td><%= article.rank %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>
</div>

app/views/articles/new.html.erb
<div class = 'article'>
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div class = 'article'>
<p id="notice"><%= notice %></p>

<p class = "article_title">
  <%= @article.title %>
</p>

<p class = "article_date">
    <%= @article.created_at.to_s[0,10] %>
</p>

<p class = "article_author">
  <%= @authors.find(@article.author_id).name %>
</p>

<p class = "article_topic">
  <%= @article.topic %>
</p>

<p>
  <%= raw simple_format h(@article.content) %>
</p>

<!--<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>-->
</div>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<div class = 'article'>
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>
</div>

app/views/authors/index.html.erb
<div class = 'article'>
<h1>Listing authors</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Summary</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.summary %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>
</div>

app/views/authors/new.html.erb
<div class = 'article'>
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>
</div>

app/views/authors/show.html.erb
<div class = 'article'>
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @author.summary %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwentiesTimes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div id = 'container'>
        <div id = 'header'> 
            <div id = 'title'><%= link_to :root do %><font color='#00688B'>twenties</font>times<% end %></div>
            <div id = 'tagline'><font color="#BBB">news feed for a twenty-something.</font></div>
            
            <ul id = 'navigation'> 
                    <% if params[:controller] == 'articles' %>
                    <li id = 'about_nav'> <%= link_to 'Back', :back %> <li>
                    <% else %>
                    <li id = 'topic_nav'> topics
                        <ul>
                            <li>  <%= link_to 'science', {:controller => 'static_pages', :action => 'science'} %> </li>
                            <li>  <%= link_to 'art', {:controller => 'static_pages', :action => 'art'} %> </li>
                            <li>  <%= link_to 'politics', {:controller => 'static_pages', :action => 'politics'} %> </li>
                            <li>  <%= link_to 'coding', {:controller => 'static_pages', :action => 'coding'} %> </li>
                            <li>  <%= link_to 'books', {:controller => 'static_pages', :action => 'books'} %> </li>
                            <li>  <%= link_to 'stories', {:controller => 'static_pages', :action => 'stories'} %> </li>
                            <li>  <%= link_to 'music', {:controller => 'static_pages', :action => 'music'} %> </li>
                        </ul>
                    </li>
                    <li id = 'writers_nav'> writers 
                        <ul>
                            <% @authors.each do |author| %>
                                <%= link_to(author) do %>
                                    <li><%= author.name %></li>
                                <% end %>    
                            <% end %>
                        </ul>
                    </li>
                    <li id = 'about_nav'> about us </li>
                    <li id = 'contact_nav'> contact </li>
                    <% end %>
                </ul>
            
            <div id = 'icons'>
                <img src="http://www.candygramformongo.com/_img/home/facebook-icon.gif" height = '25px' width = '25px'></img>
                <img src="http://www.ala.org/conferencesevents/sites/ala.org.conferencesevents/files/content/celebrationweeks/natlibraryweek/twitter-icon.png" height = '25px' width = '25px'></img>
            </div>
        
        </div>

        <div id = 'content_container'>
            <%= yield %>
        </div>

        <div id = 'footer'>
            <ul>
                <li>Volunteer as a Contributer!</li>
                <li>@2013 20sTimes</li>
            </ul>
        </div>
    </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @article.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@article.errors.count, "error") %>.
    </div>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/art.html.erb
<div id = 'load_container'>
    <% @articles.each do |article| %>                
        <% if article.topic == 'art' %>
        <div class = 'article'>
            <div class = 'article_title'>
                <%= link_to(article) do %>
                  <strong><%= article.title %></strong>
                <% end %></div> 
            <div class = 'article_date'><%= article.created_at.to_s[0,10] %></div>
            <div class = 'article_author'> By <%= Author.find(article.author_id).name %> </div>
            <div class = 'article_topic'><%= article.topic[1] %></div>
            </br>
            <!--<%= raw simple_format h(article.content) %>-->
        </div>
        </br>
        </br>
        <% end %>
    <% end %>
</div>

app/views/static_pages/books.html.erb
<div id = 'load_container'>
    <% @articles.each do |article| %>                
        <% if article.topic == 'books' %>
        <div class = 'article'>
            <div class = 'article_title'>
                <%= link_to(article) do %>
                  <strong><%= article.title %></strong>
                <% end %></div> 
            <div class = 'article_date'><%= article.created_at.to_s[0,10] %></div>
            <div class = 'article_author'> By <%= Author.find(article.author_id).name %> </div>
            <div class = 'article_topic'><%= article.topic[1] %></div>
            </br>
            <!--<%= raw simple_format h(article.content) %>-->
        </div>
        </br>
        </br>
        <% end %>
    <% end %>
</div>

app/views/static_pages/coding.html.erb
<div id = 'load_container'>
    <% @articles.each do |article| %>                
        <% if article.topic == 'coding' %>
        <div class = 'article'>
            <div class = 'article_title'>
                <%= link_to(article) do %>
                  <strong><%= article.title %></strong>
                <% end %></div> 
            <div class = 'article_date'><%= article.created_at.to_s[0,10] %></div>
            <div class = 'article_author'> By <%= Author.find(article.author_id).name %> </div>
            <div class = 'article_topic'><%= article.topic[1] %></div>
            </br>
            <!--<%= raw simple_format h(article.content) %>-->
        </div>
        </br>
        </br>
        <% end %>
    <% end %>
</div>

app/views/static_pages/home.html.erb
<div id = 'major_articles'>
    <% @articles.each do |article| %>
      <% if article.rank == 1%>
       <div class = 'article'>
        <div class = 'article_title'>
            <%= link_to(article) do %>
              <strong><%= article.title %></strong>
            <% end %>
        </div> 
        <div class = 'article_date'><%= article.created_at.to_s[0,10] %></div>
        <div class = 'article_author'> By <%= Author.find(article.author_id).name %> </div>
        <div class = 'article_topic'><%= article.topic %></div>
        </br>
        <!--<%= raw simple_format h(article.content) %>-->
      </div>
      </br>
      <% end %>
    <% end %>
</div>

<div id = 'minor_articles'> 
    <% @articles.each do |article| %>
      <% if article.rank == 2%>
      <div class = 'article'>
        <div class = 'article_title'>
            <%= link_to(article) do %>
              <strong><%= article.title %></strong>
            <% end %>
        </div> 
        <div class = 'article_date'><%= article.created_at.to_s[0,10] %></div>
        <div class = 'article_author'> By <%= Author.find(article.author_id).name %> </div>
        <div class = 'article_topic'><%= article.topic %></div>
        </br>
        <!--<%= raw simple_format h(article.content) %>-->
      </div>
      </br>
      <% end %>
    <% end %>
</div>

app/views/static_pages/music.html.erb
<div id = 'load_container'>
    <% @articles.each do |article| %>                
        <% if article.topic == 'music' %>
        <div class = 'article'>
            <div class = 'article_title'>
                <%= link_to(article) do %>
                  <strong><%= article.title %></strong>
                <% end %></div> 
            <div class = 'article_date'><%= article.created_at.to_s[0,10] %></div>
            <div class = 'article_author'> By <%= Author.find(article.author_id).name %> </div>
            <div class = 'article_topic'><%= article.topic[1] %></div>
            </br>
            <!--<%= raw simple_format h(article.content) %>-->
        </div>
        </br>
        </br>
        <% end %>
    <% end %>
</div>

app/views/static_pages/politics.html.erb
<div id = 'load_container'>
    <% @articles.each do |article| %>                
        <% if article.topic == 'politics' %>
        <div class = 'article'>
            <div class = 'article_title'>
                <%= link_to(article) do %>
                  <strong><%= article.title %></strong>
                <% end %></div> 
            <div class = 'article_date'><%= article.created_at.to_s[0,10] %></div>
            <div class = 'article_author'> By <%= Author.find(article.author_id).name %> </div>
            <div class = 'article_topic'><%= article.topic[1] %></div>
            </br>
            <!--<%= raw simple_format h(article.content) %>-->
        </div>
        </br>
        </br>
        <% end %>
    <% end %>
</div>

app/views/static_pages/science.html.erb
<div id = 'load_container'>
    <% @articles.each do |article| %>                
        <% if article.topic == 'science' %>
        <div class = 'article'>
            <div class = 'article_title'>
                <%= link_to(article) do %>
                  <strong><%= article.title %></strong>
                <% end %></div> 
            <div class = 'article_date'><%= article.created_at.to_s[0,10] %></div>
            <div class = 'article_author'> By <%= Author.find(article.author_id).name %> </div>
            <div class = 'article_topic'><%= article.topic[1] %></div>
            </br>
            <!--<%= raw simple_format h(article.content) %>-->
        </div>
        </br>
        </br>
        <% end %>
    <% end %>
</div>

app/views/static_pages/stories.html.erb
<div id = 'load_container'>
    <% @articles.each do |article| %>                
        <% if article.topic == 'stories' %>
        <div class = 'article'>
            <div class = 'article_title'>
                <%= link_to(article) do %>
                  <strong><%= article.title %></strong>
                <% end %></div> 
            <div class = 'article_date'><%= article.created_at.to_s[0,10] %></div>
            <div class = 'article_author'> By <%= Author.find(article.author_id).name %> </div>
            <div class = 'article_topic'><%= article.topic[1] %></div>
            </br>
            <!--<%= raw simple_format h(article.content) %>-->
        </div>
        </br>
        </br>
        <% end %>
    <% end %>
</div>

app/views/static_pages/topics.html.erb
<div id = 'load_container'>
     <% @topics.each do |topic| %>
        <div id = "<%= topic[0] %>">
            <% @articles.each do |article| %>                
                <% if article.topic == topic[0] %>
                <div class = 'article'>
                    <div class = 'article_title'>
                        <%= link_to(article) do %>
                          <strong><%= article.title %></strong>
                        <% end %></div> 
                    <div class = 'article_date'><%= article.created_at.to_s[0,10] %></div>
                    <div class = 'article_author'> By <%= Author.find(article.author_id).name %> </div>
                    <div class = 'article_topic'><%= article.topic[1] %></div>
                    </br>
                    <!--<%= raw simple_format h(article.content) %>-->
                </div>
                </br>
                </br>
                <% end %>
            <% end %>
        </div>
     <% end %>
     
     <% @authors.each do |author| %>
        <div id = "<%= author.name.downcase.gsub(' ', '_') %>">
            <% @articles.each do |article| %>
                <% if article.author_id == author.id %>
                <div class = 'article'>
                    <div class = 'article_title'>
                        <%= link_to(article) do %>
                          <strong><%= article.title %></strong>
                        <% end %></div> 
                    <div class = 'article_date'><%= article.created_at.to_s[0,10] %></div>
                    <div class = 'article_author'> By <%= Author.find(article.author_id).name %> </div>
                    <div class = 'article_topic'><%= article.topic[0] %></div>
                    </br>
                    <!--<%= raw simple_format h(article.content) %>-->
                </div>
                </br>
                </br>
                <% end %>
            <% end %>
        </div>
     <% end %>   
</div>

app/views/writers/_form.html.erb
<%= form_for(@writer) do |f| %>
  <% if @writer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@writer.errors.count, "error") %> prohibited this writer from being saved:</h2>

      <ul>
      <% @writer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/writers/edit.html.erb
<h1>Editing writer</h1>

<%= render 'form' %>

<%= link_to 'Show', @writer %> |
<%= link_to 'Back', writers_path %>

app/views/writers/index.html.erb
<h1>Listing writers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Summary</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @writers.each do |writer| %>
      <tr>
        <td><%= writer.first_name %></td>
        <td><%= writer.last_name %></td>
        <td><%= writer.summary %></td>
        <td><%= link_to 'Show', writer %></td>
        <td><%= link_to 'Edit', edit_writer_path(writer) %></td>
        <td><%= link_to 'Destroy', writer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Writer', new_writer_path %>

app/views/writers/new.html.erb
<h1>New writer</h1>

<%= render 'form' %>

<%= link_to 'Back', writers_path %>

app/views/writers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @writer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @writer.last_name %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @writer.summary %>
</p>

<%= link_to 'Edit', edit_writer_path(@writer) %> |
<%= link_to 'Back', writers_path %>